from typing import Union

from unimport.statement import Import, ImportFrom, Name

__all__ = ["NAMES", "IMPORTS", "UNUSED_IMPORTS"]


NAMES: list[Name] = [
    Name(lineno=2, name="cond", is_all=False),
    Name(lineno=3, name="a1", is_all=False),
    Name(lineno=4, name="print", is_all=False),
    Name(lineno=4, name="a1", is_all=False),
    Name(lineno=9, name="a2", is_all=False),
    Name(lineno=10, name="a2", is_all=False),
    Name(lineno=13, name="a3", is_all=False),
    Name(lineno=14, name="a3", is_all=False),
    Name(lineno=17, name="a4", is_all=False),
    Name(lineno=17, name="a4.path", is_all=False),
    Name(lineno=21, name="a5", is_all=False),
    Name(lineno=21, name="a5", is_all=False),
    Name(lineno=24, name="a6", is_all=False),
    Name(lineno=26, name="a6", is_all=False),
    Name(lineno=30, name="a7", is_all=False),
    Name(lineno=30, name="x", is_all=False),
    Name(lineno=31, name="Exception", is_all=False),
    Name(lineno=33, name="print", is_all=False),
    Name(lineno=33, name="a7", is_all=False),
    Name(lineno=36, name="ctx", is_all=False),
    Name(lineno=36, name="a8", is_all=False),
    Name(lineno=38, name="print", is_all=False),
    Name(lineno=38, name="a8", is_all=False),
    Name(lineno=41, name="a9", is_all=False),
    Name(lineno=42, name="print", is_all=False),
    Name(lineno=42, name="a9", is_all=False),
    Name(lineno=45, name="a10", is_all=False),
    Name(lineno=45, name="str", is_all=False),
    Name(lineno=46, name="print", is_all=False),
    Name(lineno=46, name="a10", is_all=False),
    Name(lineno=49, name="x11", is_all=False),
    Name(lineno=49, name="a11", is_all=False),
    Name(lineno=49, name="_", is_all=False),
    Name(lineno=49, name="range", is_all=False),
    Name(lineno=53, name="a12", is_all=False),
    Name(lineno=52, name="a12.decorator", is_all=False),
    Name(lineno=57, name="a13", is_all=False),
    Name(lineno=58, name="a13", is_all=False),
    Name(lineno=56, name="a13.T", is_all=False),
    Name(lineno=61, name="a14", is_all=False),
    Name(lineno=64, name="a15", is_all=False),
    Name(lineno=66, name="print", is_all=False),
    Name(lineno=66, name="a15", is_all=False),
]
IMPORTS: list[Union[Import, ImportFrom]] = [
    Import(lineno=1, column=1, name="a1", package="a1"),
    Import(lineno=6, column=1, name="a2", package="a2"),
    Import(lineno=12, column=1, name="a3", package="a3"),
    Import(lineno=16, column=1, name="a4", package="a4"),
    Import(lineno=19, column=1, name="a5", package="a5"),
    Import(lineno=23, column=1, name="a6", package="a6"),
    Import(lineno=28, column=1, name="a7", package="a7"),
    Import(lineno=35, column=1, name="a8", package="a8"),
    Import(lineno=40, column=1, name="a9", package="a9"),
    Import(lineno=44, column=1, name="a10", package="a10"),
    Import(lineno=48, column=1, name="a11", package="a11"),
    Import(lineno=51, column=1, name="a12", package="a12"),
    Import(lineno=55, column=1, name="a13", package="a13"),
    Import(lineno=60, column=1, name="a14", package="a14"),
    Import(lineno=63, column=1, name="a15", package="a15"),
]
UNUSED_IMPORTS: list[Union[Import, ImportFrom]] = []
