- id: unimport
  name: unimport
  description: "A linter & formatter for finding & removing unused import statements"
  entry: unimport
  language: python
  language_version: python3
  verbose: true
  types: [python]
