- id: unimport
  name: unimport
  description:
    "🚀 The ultimate linter and formatter for removing unused import statements in your
    code."
  entry: unimport
  language: python
  language_version: python3
  types: [python]
