- id: unimport
  name: unimport
  description: "A linter, formatter for finding and removing unused import statements"
  entry: unimport
  language: python
  language_version: python3
  types: [python]
  args: ["--remove"]
