coverage:
  status:
    project:
      default: false # disable the default status that measures entire project
      tests: # declare a new status context "tests"
        target: 100% # we always want 100% coverage here
        paths: ["tests/"] # only include coverage in "tests/" folder
      unimport: # declare a new status context "unimport"
        paths: ["unimport/", "!tests/"] # remove all files in "tests/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
  branches: # branch names that can post comment
    - "master"
