name: build-docs
on:
  push:
    tags:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Install  Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]

      - name: Build Docs
        run: |
          git config --local user.email "hakancelikdev@gmail.com"
          git config --local user.name "Hakan Celik"
          git fetch --all
          mike deploy ${{github.ref_name}} latest --update-aliases --push
