name: Package Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - stable

    # Publish `1.2.3` tags as releases.
    tags:
      - "**"

env:
  IMAGE_NAME: unimport

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run:
          docker build . --file Dockerfile --tag $IMAGE_NAME --label
          "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        # This is where you will update the PAT to GH_TOKEN
        run:
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}
          --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          # [ "$VERSION" == "stable" ] && VERSION=stable

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
