name: unimport
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
      - name: unimport
        uses: ./
        with:
          extra_args: --include src/
